export * from './About'
export * from './Blog'
export * from './Blog/[slug]'
export * from './Contact'
export * from './Home'
export * from './NotFound'
export * from './Work/[id]'
export * from './Work'
